server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: consumer-route
          uri: lb://consumer
          predicates: Path= /consumer/**
          filters: StripPrefix= 1
        - id: provider-route
          uri: lb://provider
          predicates: Path= /provider/**
          filters: StripPrefix= 1
        - id: member-route
          uri: lb://member
          predicates: Path= /member/**
          filters: StripPrefix= 1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway-local
    ip-address: 1.117.73.217
  client:
    service-url:
      defaultZone: http://47.98.62.32:8081/eureka,http://1.117.73.217:8081/eureka