server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: consumer-route
          uri: http://localhost:81
          predicates: Path= /consumer/**
          filters: StripPrefix= 1
        - id: provider-route
          uri: lb://provider
          predicates: Path= /provider/**
          filters: StripPrefix= 1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway-80
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/